#!/bin/bash
set -e
if [[ " $* " =~ " --relaxed " ]]; then
    export RELAXED_WARNINGS=1
fi
source "$(dirname "$0")/_env"
RUSTDOCFLAGS="$WASM32_RUSTDOCFLAGS" cargo +nightly doc --target=wasm32-unknown-unknown
